//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:33:42 AM CEST 
//


package kdpw.xsd.trar_ins_002;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Podstawowe informacje o stronach transakcji
 * 
 * <p>Java class for CounterpartyIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CounterpartyIdentification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CtrPtyTRId" type="{urn:kdpw:xsd:trar.ins.002.02}TRInstitutionCode" minOccurs="0"/&gt;
 *         &lt;element name="ClrMmbId" type="{urn:kdpw:xsd:trar.ins.002.02}InstitutionCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CounterpartyIdentification", propOrder = {
    "ctrPtyTRId",
    "clrMmbId"
})
public class CounterpartyIdentification {

    @XmlElement(name = "CtrPtyTRId")
    protected TRInstitutionCode ctrPtyTRId;
    @XmlElement(name = "ClrMmbId")
    protected InstitutionCode clrMmbId;

    /**
     * Gets the value of the ctrPtyTRId property.
     * 
     * @return
     *     possible object is
     *     {@link TRInstitutionCode }
     *     
     */
    public TRInstitutionCode getCtrPtyTRId() {
        return ctrPtyTRId;
    }

    /**
     * Sets the value of the ctrPtyTRId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRInstitutionCode }
     *     
     */
    public void setCtrPtyTRId(TRInstitutionCode value) {
        this.ctrPtyTRId = value;
    }

    /**
     * Gets the value of the clrMmbId property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionCode }
     *     
     */
    public InstitutionCode getClrMmbId() {
        return clrMmbId;
    }

    /**
     * Sets the value of the clrMmbId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionCode }
     *     
     */
    public void setClrMmbId(InstitutionCode value) {
        this.clrMmbId = value;
    }

}
