//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.05 at 10:55:54 PM CEST 
//


package kdpw.xsd.trar_sts_003;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Linkages to related messages
 * 
 * <p>Java class for Linkages complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Linkages"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PrvsSndrMsgRef" type="{urn:kdpw:xsd:trar.sts.003.02}Max16Text"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Linkages", propOrder = {
    "prvsSndrMsgRef"
})
public class Linkages {

    @XmlElement(name = "PrvsSndrMsgRef", required = true)
    protected String prvsSndrMsgRef;

    /**
     * Gets the value of the prvsSndrMsgRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrvsSndrMsgRef() {
        return prvsSndrMsgRef;
    }

    /**
     * Sets the value of the prvsSndrMsgRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrvsSndrMsgRef(String value) {
        this.prvsSndrMsgRef = value;
    }

}
