//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.05 at 10:55:54 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:kdpw:xsd:trar.sts.003.02", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kdpw.xsd.trar_sts_003;
