//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:33:45 AM CEST 
//


package kdpw.xsd.trar_rcn_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Informacje ogólne
 * 
 * <p>Java class for GeneralInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SndrMsgRef" type="{urn:kdpw:xsd:trar.rcn.001.02}Max16Text"/&gt;
 *         &lt;element name="FuncOfMsg" type="{urn:kdpw:xsd:trar.rcn.001.02}FunctionOfMessage"/&gt;
 *         &lt;element name="CreDtTm" type="{urn:kdpw:xsd:trar.rcn.001.02}DateAndDateTimeChoice"/&gt;
 *         &lt;element name="ParDtTm" type="{urn:kdpw:xsd:trar.rcn.001.02}DateAndDateTimeChoice"/&gt;
 *         &lt;element name="CompDtTm" type="{urn:kdpw:xsd:trar.rcn.001.02}DateAndDateTimeChoice" minOccurs="0"/&gt;
 *         &lt;element name="EligDtTm" type="{urn:kdpw:xsd:trar.rcn.001.02}DateAndDateTimeChoice"/&gt;
 *         &lt;element name="Lnk" type="{urn:kdpw:xsd:trar.rcn.001.02}Linkages"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralInformation", propOrder = {
    "sndrMsgRef",
    "funcOfMsg",
    "creDtTm",
    "parDtTm",
    "compDtTm",
    "eligDtTm",
    "lnk"
})
public class GeneralInformation {

    @XmlElement(name = "SndrMsgRef", required = true)
    protected String sndrMsgRef;
    @XmlElement(name = "FuncOfMsg", required = true)
    @XmlSchemaType(name = "string")
    protected FunctionOfMessage funcOfMsg;
    @XmlElement(name = "CreDtTm", required = true)
    protected DateAndDateTimeChoice creDtTm;
    @XmlElement(name = "ParDtTm", required = true)
    protected DateAndDateTimeChoice parDtTm;
    @XmlElement(name = "CompDtTm")
    protected DateAndDateTimeChoice compDtTm;
    @XmlElement(name = "EligDtTm", required = true)
    protected DateAndDateTimeChoice eligDtTm;
    @XmlElement(name = "Lnk", required = true)
    protected Linkages lnk;

    /**
     * Gets the value of the sndrMsgRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndrMsgRef() {
        return sndrMsgRef;
    }

    /**
     * Sets the value of the sndrMsgRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndrMsgRef(String value) {
        this.sndrMsgRef = value;
    }

    /**
     * Gets the value of the funcOfMsg property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionOfMessage }
     *     
     */
    public FunctionOfMessage getFuncOfMsg() {
        return funcOfMsg;
    }

    /**
     * Sets the value of the funcOfMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionOfMessage }
     *     
     */
    public void setFuncOfMsg(FunctionOfMessage value) {
        this.funcOfMsg = value;
    }

    /**
     * Gets the value of the creDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public DateAndDateTimeChoice getCreDtTm() {
        return creDtTm;
    }

    /**
     * Sets the value of the creDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public void setCreDtTm(DateAndDateTimeChoice value) {
        this.creDtTm = value;
    }

    /**
     * Gets the value of the parDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public DateAndDateTimeChoice getParDtTm() {
        return parDtTm;
    }

    /**
     * Sets the value of the parDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public void setParDtTm(DateAndDateTimeChoice value) {
        this.parDtTm = value;
    }

    /**
     * Gets the value of the compDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public DateAndDateTimeChoice getCompDtTm() {
        return compDtTm;
    }

    /**
     * Sets the value of the compDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public void setCompDtTm(DateAndDateTimeChoice value) {
        this.compDtTm = value;
    }

    /**
     * Gets the value of the eligDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public DateAndDateTimeChoice getEligDtTm() {
        return eligDtTm;
    }

    /**
     * Sets the value of the eligDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public void setEligDtTm(DateAndDateTimeChoice value) {
        this.eligDtTm = value;
    }

    /**
     * Gets the value of the lnk property.
     * 
     * @return
     *     possible object is
     *     {@link Linkages }
     *     
     */
    public Linkages getLnk() {
        return lnk;
    }

    /**
     * Sets the value of the lnk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Linkages }
     *     
     */
    public void setLnk(Linkages value) {
        this.lnk = value;
    }

}
