//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.14 at 01:33:14 PM CEST 
//


package kdpw.xsd.trar_sts_001;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Floating rate related information.
 * 
 * <p>Java class for FloatingRate_TR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FloatingRate_TR"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Rate" type="{urn:kdpw:xsd:trar.sts.001.03}Max25Text" minOccurs="0"/&gt;
 *         &lt;element name="RefFrqcyTmPrd" type="{urn:kdpw:xsd:trar.sts.001.03}RateBasis1Code_TR" minOccurs="0"/&gt;
 *         &lt;element name="RefFrqcyMltplr" type="{urn:kdpw:xsd:trar.sts.001.03}Max3Number" minOccurs="0"/&gt;
 *         &lt;element name="PmtFrqcyTmPrd" type="{urn:kdpw:xsd:trar.sts.001.03}RateBasis1Code_TR" minOccurs="0"/&gt;
 *         &lt;element name="PmtFrqcyMltplr" type="{urn:kdpw:xsd:trar.sts.001.03}Max3Number" minOccurs="0"/&gt;
 *         &lt;element name="RstFrqcyTmPrd" type="{urn:kdpw:xsd:trar.sts.001.03}RateBasis1Code_TR" minOccurs="0"/&gt;
 *         &lt;element name="RstFrqcyMltplr" type="{urn:kdpw:xsd:trar.sts.001.03}Max3Number" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FloatingRate_TR", propOrder = {
    "rate",
    "refFrqcyTmPrd",
    "refFrqcyMltplr",
    "pmtFrqcyTmPrd",
    "pmtFrqcyMltplr",
    "rstFrqcyTmPrd",
    "rstFrqcyMltplr"
})
public class FloatingRateTR {

    @XmlElement(name = "Rate")
    protected String rate;
    @XmlElement(name = "RefFrqcyTmPrd")
    @XmlSchemaType(name = "string")
    protected RateBasis1CodeTR refFrqcyTmPrd;
    @XmlElement(name = "RefFrqcyMltplr")
    protected BigDecimal refFrqcyMltplr;
    @XmlElement(name = "PmtFrqcyTmPrd")
    @XmlSchemaType(name = "string")
    protected RateBasis1CodeTR pmtFrqcyTmPrd;
    @XmlElement(name = "PmtFrqcyMltplr")
    protected BigDecimal pmtFrqcyMltplr;
    @XmlElement(name = "RstFrqcyTmPrd")
    @XmlSchemaType(name = "string")
    protected RateBasis1CodeTR rstFrqcyTmPrd;
    @XmlElement(name = "RstFrqcyMltplr")
    protected BigDecimal rstFrqcyMltplr;

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRate(String value) {
        this.rate = value;
    }

    /**
     * Gets the value of the refFrqcyTmPrd property.
     * 
     * @return
     *     possible object is
     *     {@link RateBasis1CodeTR }
     *     
     */
    public RateBasis1CodeTR getRefFrqcyTmPrd() {
        return refFrqcyTmPrd;
    }

    /**
     * Sets the value of the refFrqcyTmPrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateBasis1CodeTR }
     *     
     */
    public void setRefFrqcyTmPrd(RateBasis1CodeTR value) {
        this.refFrqcyTmPrd = value;
    }

    /**
     * Gets the value of the refFrqcyMltplr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRefFrqcyMltplr() {
        return refFrqcyMltplr;
    }

    /**
     * Sets the value of the refFrqcyMltplr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRefFrqcyMltplr(BigDecimal value) {
        this.refFrqcyMltplr = value;
    }

    /**
     * Gets the value of the pmtFrqcyTmPrd property.
     * 
     * @return
     *     possible object is
     *     {@link RateBasis1CodeTR }
     *     
     */
    public RateBasis1CodeTR getPmtFrqcyTmPrd() {
        return pmtFrqcyTmPrd;
    }

    /**
     * Sets the value of the pmtFrqcyTmPrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateBasis1CodeTR }
     *     
     */
    public void setPmtFrqcyTmPrd(RateBasis1CodeTR value) {
        this.pmtFrqcyTmPrd = value;
    }

    /**
     * Gets the value of the pmtFrqcyMltplr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPmtFrqcyMltplr() {
        return pmtFrqcyMltplr;
    }

    /**
     * Sets the value of the pmtFrqcyMltplr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPmtFrqcyMltplr(BigDecimal value) {
        this.pmtFrqcyMltplr = value;
    }

    /**
     * Gets the value of the rstFrqcyTmPrd property.
     * 
     * @return
     *     possible object is
     *     {@link RateBasis1CodeTR }
     *     
     */
    public RateBasis1CodeTR getRstFrqcyTmPrd() {
        return rstFrqcyTmPrd;
    }

    /**
     * Sets the value of the rstFrqcyTmPrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateBasis1CodeTR }
     *     
     */
    public void setRstFrqcyTmPrd(RateBasis1CodeTR value) {
        this.rstFrqcyTmPrd = value;
    }

    /**
     * Gets the value of the rstFrqcyMltplr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRstFrqcyMltplr() {
        return rstFrqcyMltplr;
    }

    /**
     * Sets the value of the rstFrqcyMltplr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRstFrqcyMltplr(BigDecimal value) {
        this.rstFrqcyMltplr = value;
    }

}
