//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 01:49:48 PM CET 
//


package kdpw.xsd.trar_sts_001;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Powiązania z innymi komunikatami
 * 
 * <p>Java class for Linkages complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Linkages"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RltdRef" type="{urn:kdpw:xsd:trar.sts.001.02}RelatedReference" minOccurs="0"/&gt;
 *         &lt;element name="RltdReqRef" type="{urn:kdpw:xsd:trar.sts.001.02}Max16Text" minOccurs="0"/&gt;
 *         &lt;element name="TradRefId" type="{urn:kdpw:xsd:trar.sts.001.02}TradeReference" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Linkages", propOrder = {
    "rltdRef",
    "rltdReqRef",
    "tradRefId"
})
public class Linkages {

    @XmlElement(name = "RltdRef")
    protected RelatedReference rltdRef;
    @XmlElement(name = "RltdReqRef")
    protected String rltdReqRef;
    @XmlElement(name = "TradRefId")
    protected List<TradeReference> tradRefId;

    /**
     * Gets the value of the rltdRef property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedReference }
     *     
     */
    public RelatedReference getRltdRef() {
        return rltdRef;
    }

    /**
     * Sets the value of the rltdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedReference }
     *     
     */
    public void setRltdRef(RelatedReference value) {
        this.rltdRef = value;
    }

    /**
     * Gets the value of the rltdReqRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRltdReqRef() {
        return rltdReqRef;
    }

    /**
     * Sets the value of the rltdReqRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRltdReqRef(String value) {
        this.rltdReqRef = value;
    }

    /**
     * Gets the value of the tradRefId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tradRefId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTradRefId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TradeReference }
     * 
     * 
     */
    public List<TradeReference> getTradRefId() {
        if (tradRefId == null) {
            tradRefId = new ArrayList<>();
        }
        return this.tradRefId;
    }

}
