//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 11:10:33 AM CEST 
//


package kdpw.xsd.trar_sts_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kdpw.xsd.trar_sts_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KDPWDocument_QNAME = new QName("urn:kdpw:xsd:trar.sts.001.03", "KDPWDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kdpw.xsd.trar_sts_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KDPWDocument }
     * 
     */
    public KDPWDocument createKDPWDocument() {
        return new KDPWDocument();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAnd20Amount }
     * 
     */
    public ActiveCurrencyAnd20Amount createActiveCurrencyAnd20Amount() {
        return new ActiveCurrencyAnd20Amount();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAnd20AmountN }
     * 
     */
    public ActiveCurrencyAnd20AmountN createActiveCurrencyAnd20AmountN() {
        return new ActiveCurrencyAnd20AmountN();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAnd20Amount }
     * 
     */
    public ActiveOrHistoricCurrencyAnd20Amount createActiveOrHistoricCurrencyAnd20Amount() {
        return new ActiveOrHistoricCurrencyAnd20Amount();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAnd20AmountNegative }
     * 
     */
    public ActiveOrHistoricCurrencyAnd20AmountNegative createActiveOrHistoricCurrencyAnd20AmountNegative() {
        return new ActiveOrHistoricCurrencyAnd20AmountNegative();
    }

    /**
     * Create an instance of {@link AssetClassAttributes1Choice1 }
     * 
     */
    public AssetClassAttributes1Choice1 createAssetClassAttributes1Choice1() {
        return new AssetClassAttributes1Choice1();
    }

    /**
     * Create an instance of {@link CommodityTrade }
     * 
     */
    public CommodityTrade createCommodityTrade() {
        return new CommodityTrade();
    }

    /**
     * Create an instance of {@link CommonTradeDataReport171 }
     * 
     */
    public CommonTradeDataReport171 createCommonTradeDataReport171() {
        return new CommonTradeDataReport171();
    }

    /**
     * Create an instance of {@link ContractType31 }
     * 
     */
    public ContractType31 createContractType31() {
        return new ContractType31();
    }

    /**
     * Create an instance of {@link ContractDetailsTRN }
     * 
     */
    public ContractDetailsTRN createContractDetailsTRN() {
        return new ContractDetailsTRN();
    }

    /**
     * Create an instance of {@link ContractValuationDataTRN }
     * 
     */
    public ContractValuationDataTRN createContractValuationDataTRN() {
        return new ContractValuationDataTRN();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRN }
     * 
     */
    public CounterpartySpecificDataTRN createCounterpartySpecificDataTRN() {
        return new CounterpartySpecificDataTRN();
    }

    /**
     * Create an instance of {@link CounterpartyTRN }
     * 
     */
    public CounterpartyTRN createCounterpartyTRN() {
        return new CounterpartyTRN();
    }

    /**
     * Create an instance of {@link CounterpartyOtherTRN }
     * 
     */
    public CounterpartyOtherTRN createCounterpartyOtherTRN() {
        return new CounterpartyOtherTRN();
    }

    /**
     * Create an instance of {@link CreditDerivativeTR }
     * 
     */
    public CreditDerivativeTR createCreditDerivativeTR() {
        return new CreditDerivativeTR();
    }

    /**
     * Create an instance of {@link CurrencyExchange101 }
     * 
     */
    public CurrencyExchange101 createCurrencyExchange101() {
        return new CurrencyExchange101();
    }

    /**
     * Create an instance of {@link DateAndDateTimeChoice }
     * 
     */
    public DateAndDateTimeChoice createDateAndDateTimeChoice() {
        return new DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link DerivativeForeignExchange2 }
     * 
     */
    public DerivativeForeignExchange2 createDerivativeForeignExchange2() {
        return new DerivativeForeignExchange2();
    }

    /**
     * Create an instance of {@link DerivativeInterest2 }
     * 
     */
    public DerivativeInterest2 createDerivativeInterest2() {
        return new DerivativeInterest2();
    }

    /**
     * Create an instance of {@link EnergyDeliveryAttribute31 }
     * 
     */
    public EnergyDeliveryAttribute31 createEnergyDeliveryAttribute31() {
        return new EnergyDeliveryAttribute31();
    }

    /**
     * Create an instance of {@link ExchangeRateBasis1 }
     * 
     */
    public ExchangeRateBasis1 createExchangeRateBasis1() {
        return new ExchangeRateBasis1();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantity24Choice2 }
     * 
     */
    public FinancialInstrumentQuantity24Choice2 createFinancialInstrumentQuantity24Choice2() {
        return new FinancialInstrumentQuantity24Choice2();
    }

    /**
     * Create an instance of {@link FixedRateTR }
     * 
     */
    public FixedRateTR createFixedRateTR() {
        return new FixedRateTR();
    }

    /**
     * Create an instance of {@link FloatingRateTR }
     * 
     */
    public FloatingRateTR createFloatingRateTR() {
        return new FloatingRateTR();
    }

    /**
     * Create an instance of {@link FloatingRateIdentification1Choice }
     * 
     */
    public FloatingRateIdentification1Choice createFloatingRateIdentification1Choice() {
        return new FloatingRateIdentification1Choice();
    }

    /**
     * Create an instance of {@link GeneralInformation }
     * 
     */
    public GeneralInformation createGeneralInformation() {
        return new GeneralInformation();
    }

    /**
     * Create an instance of {@link InterestRate11Choice1 }
     * 
     */
    public InterestRate11Choice1 createInterestRate11Choice1() {
        return new InterestRate11Choice1();
    }

    /**
     * Create an instance of {@link InterestRateLegs41 }
     * 
     */
    public InterestRateLegs41 createInterestRateLegs41() {
        return new InterestRateLegs41();
    }

    /**
     * Create an instance of {@link Linkages }
     * 
     */
    public Linkages createLinkages() {
        return new Linkages();
    }

    /**
     * Create an instance of {@link MasterAgreementTR }
     * 
     */
    public MasterAgreementTR createMasterAgreementTR() {
        return new MasterAgreementTR();
    }

    /**
     * Create an instance of {@link OptionTR }
     * 
     */
    public OptionTR createOptionTR() {
        return new OptionTR();
    }

    /**
     * Create an instance of {@link OrganisationIdentification3Choice1 }
     * 
     */
    public OrganisationIdentification3Choice1 createOrganisationIdentification3Choice1() {
        return new OrganisationIdentification3Choice1();
    }

    /**
     * Create an instance of {@link Period101 }
     * 
     */
    public Period101 createPeriod101() {
        return new Period101();
    }

    /**
     * Create an instance of {@link ProductClassification1Choice }
     * 
     */
    public ProductClassification1Choice createProductClassification1Choice() {
        return new ProductClassification1Choice();
    }

    /**
     * Create an instance of {@link Reason }
     * 
     */
    public Reason createReason() {
        return new Reason();
    }

    /**
     * Create an instance of {@link ReferenceParty }
     * 
     */
    public ReferenceParty createReferenceParty() {
        return new ReferenceParty();
    }

    /**
     * Create an instance of {@link SecurityIdentification18Choice1 }
     * 
     */
    public SecurityIdentification18Choice1 createSecurityIdentification18Choice1() {
        return new SecurityIdentification18Choice1();
    }

    /**
     * Create an instance of {@link SecurityIdentification19Choice2 }
     * 
     */
    public SecurityIdentification19Choice2 createSecurityIdentification19Choice2() {
        return new SecurityIdentification19Choice2();
    }

    /**
     * Create an instance of {@link SecurityIdentification20Choice }
     * 
     */
    public SecurityIdentification20Choice createSecurityIdentification20Choice() {
        return new SecurityIdentification20Choice();
    }

    /**
     * Create an instance of {@link SecuritiesTransactionPrice7ChoiceTR }
     * 
     */
    public SecuritiesTransactionPrice7ChoiceTR createSecuritiesTransactionPrice7ChoiceTR() {
        return new SecuritiesTransactionPrice7ChoiceTR();
    }

    /**
     * Create an instance of {@link SecuritiesTransactionPrice7ChoiceTRO }
     * 
     */
    public SecuritiesTransactionPrice7ChoiceTRO createSecuritiesTransactionPrice7ChoiceTRO() {
        return new SecuritiesTransactionPrice7ChoiceTRO();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link TradeClearingTR }
     * 
     */
    public TradeClearingTR createTradeClearingTR() {
        return new TradeClearingTR();
    }

    /**
     * Create an instance of {@link TradeCollateralReportTRN }
     * 
     */
    public TradeCollateralReportTRN createTradeCollateralReportTRN() {
        return new TradeCollateralReportTRN();
    }

    /**
     * Create an instance of {@link TradeNewTransactionTR }
     * 
     */
    public TradeNewTransactionTR createTradeNewTransactionTR() {
        return new TradeNewTransactionTR();
    }

    /**
     * Create an instance of {@link TradeTransaction101 }
     * 
     */
    public TradeTransaction101 createTradeTransaction101() {
        return new TradeTransaction101();
    }

    /**
     * Create an instance of {@link TradeConfirmationTR }
     * 
     */
    public TradeConfirmationTR createTradeConfirmationTR() {
        return new TradeConfirmationTR();
    }

    /**
     * Create an instance of {@link TradeReference }
     * 
     */
    public TradeReference createTradeReference() {
        return new TradeReference();
    }

    /**
     * Create an instance of {@link TradeTransaction113 }
     * 
     */
    public TradeTransaction113 createTradeTransaction113() {
        return new TradeTransaction113();
    }

    /**
     * Create an instance of {@link TrarSts00103 }
     * 
     */
    public TrarSts00103 createTrarSts00103() {
        return new TrarSts00103();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDPWDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:kdpw:xsd:trar.sts.001.03", name = "KDPWDocument")
    public JAXBElement<KDPWDocument> createKDPWDocument(KDPWDocument value) {
        return new JAXBElement<KDPWDocument>(_KDPWDocument_QNAME, KDPWDocument.class, null, value);
    }

}
