//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.29 at 02:25:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:kdpw:xsd:trar.sts.001.03", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kdpw.xsd.trar_sts_001;
