//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.10 at 07:51:52 PM CEST 
//


package kdpw.xsd.trar_sts_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Reason
 * 
 * <p>Java class for Reason complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reason"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RsnCd" type="{urn:kdpw:xsd:trar.sts.001.03}Code4Text" minOccurs="0"/&gt;
 *         &lt;element name="RsnTxt" type="{urn:kdpw:xsd:trar.sts.001.03}Max140Text" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reason", propOrder = {
    "rsnCd",
    "rsnTxt"
})
public class Reason {

    @XmlElement(name = "RsnCd")
    protected String rsnCd;
    @XmlElement(name = "RsnTxt")
    protected String rsnTxt;

    /**
     * Gets the value of the rsnCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnCd() {
        return rsnCd;
    }

    /**
     * Sets the value of the rsnCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnCd(String value) {
        this.rsnCd = value;
    }

    /**
     * Gets the value of the rsnTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnTxt() {
        return rsnTxt;
    }

    /**
     * Sets the value of the rsnTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnTxt(String value) {
        this.rsnTxt = value;
    }

}
