//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 04:37:19 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:kdpw:xsd:admi.err.001.01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kdpw.xsd.admi_err_001;
