//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:33:45 AM CEST 
//


package kdpw.xsd.trar_ins_006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Komunikat zmiany identyfikatora Kontrahenta
 * 
 * <p>Java class for trar.ins.006.01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trar.ins.006.01"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GnlInf" type="{urn:kdpw:xsd:trar.ins.006.01}GeneralInformation"/&gt;
 *         &lt;element name="CrntCtrPtyTRId" type="{urn:kdpw:xsd:trar.ins.006.01}InstitutionCode"/&gt;
 *         &lt;element name="NewCtrPtyTRId" type="{urn:kdpw:xsd:trar.ins.006.01}TRInstitutionCode"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trar.ins.006.01", propOrder = {
    "gnlInf",
    "crntCtrPtyTRId",
    "newCtrPtyTRId"
})
public class TrarIns00601 {

    @XmlElement(name = "GnlInf", required = true)
    protected GeneralInformation gnlInf;
    @XmlElement(name = "CrntCtrPtyTRId", required = true)
    protected InstitutionCode crntCtrPtyTRId;
    @XmlElement(name = "NewCtrPtyTRId", required = true)
    protected TRInstitutionCode newCtrPtyTRId;

    /**
     * Gets the value of the gnlInf property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralInformation }
     *     
     */
    public GeneralInformation getGnlInf() {
        return gnlInf;
    }

    /**
     * Sets the value of the gnlInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralInformation }
     *     
     */
    public void setGnlInf(GeneralInformation value) {
        this.gnlInf = value;
    }

    /**
     * Gets the value of the crntCtrPtyTRId property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionCode }
     *     
     */
    public InstitutionCode getCrntCtrPtyTRId() {
        return crntCtrPtyTRId;
    }

    /**
     * Sets the value of the crntCtrPtyTRId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionCode }
     *     
     */
    public void setCrntCtrPtyTRId(InstitutionCode value) {
        this.crntCtrPtyTRId = value;
    }

    /**
     * Gets the value of the newCtrPtyTRId property.
     * 
     * @return
     *     possible object is
     *     {@link TRInstitutionCode }
     *     
     */
    public TRInstitutionCode getNewCtrPtyTRId() {
        return newCtrPtyTRId;
    }

    /**
     * Sets the value of the newCtrPtyTRId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRInstitutionCode }
     *     
     */
    public void setNewCtrPtyTRId(TRInstitutionCode value) {
        this.newCtrPtyTRId = value;
    }

}
