//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 04:42:13 PM CEST 
//


package kdpw.xsd.trar_ntf_001;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Transakcje towarowe .
 * 				Sekcja wypełniania dla kontraktów towarowych;  jeśli UPI jest raportowane i zawiera wszystkie informacje wskazane poniżej, to ta sekcja nie jest wypełniania /raportowana.
 * 			 
 * 
 * <p>Java class for CommodityTrade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommodityTrade"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CmmdtyBase" type="{urn:kdpw:xsd:trar.ntf.001.01}Max2Text" minOccurs="0"/&gt;
 *         &lt;element name="CmmdtyDtls" type="{urn:kdpw:xsd:trar.ntf.001.01}Max2Text" minOccurs="0"/&gt;
 *         &lt;element name="DlvryPnt" type="{urn:kdpw:xsd:trar.ntf.001.01}Max16Text" minOccurs="0"/&gt;
 *         &lt;element name="IntrcnnctnPnt" type="{urn:kdpw:xsd:trar.ntf.001.01}Max50Text" minOccurs="0"/&gt;
 *         &lt;element name="LdTp" type="{urn:kdpw:xsd:trar.ntf.001.01}Max2Text" minOccurs="0"/&gt;
 *         &lt;element name="DlvryStartDtTm" type="{urn:kdpw:xsd:trar.ntf.001.01}DateAndDateTimeChoice" minOccurs="0"/&gt;
 *         &lt;element name="DlvryEndDtTm" type="{urn:kdpw:xsd:trar.ntf.001.01}DateAndDateTimeChoice" minOccurs="0"/&gt;
 *         &lt;element name="CntrctCpcty" type="{urn:kdpw:xsd:trar.ntf.001.01}Max50Text" minOccurs="0"/&gt;
 *         &lt;element name="Qty" type="{urn:kdpw:xsd:trar.ntf.001.01}Max10Dec2" minOccurs="0"/&gt;
 *         &lt;element name="Pric" type="{urn:kdpw:xsd:trar.ntf.001.01}Max10Dec2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommodityTrade", propOrder = {
    "cmmdtyBase",
    "cmmdtyDtls",
    "dlvryPnt",
    "intrcnnctnPnt",
    "ldTp",
    "dlvryStartDtTm",
    "dlvryEndDtTm",
    "cntrctCpcty",
    "qty",
    "pric"
})
public class CommodityTrade {

    @XmlElement(name = "CmmdtyBase")
    protected String cmmdtyBase;
    @XmlElement(name = "CmmdtyDtls")
    protected String cmmdtyDtls;
    @XmlElement(name = "DlvryPnt")
    protected String dlvryPnt;
    @XmlElement(name = "IntrcnnctnPnt")
    protected String intrcnnctnPnt;
    @XmlElement(name = "LdTp")
    protected String ldTp;
    @XmlElement(name = "DlvryStartDtTm")
    protected DateAndDateTimeChoice dlvryStartDtTm;
    @XmlElement(name = "DlvryEndDtTm")
    protected DateAndDateTimeChoice dlvryEndDtTm;
    @XmlElement(name = "CntrctCpcty")
    protected String cntrctCpcty;
    @XmlElement(name = "Qty")
    protected BigDecimal qty;
    @XmlElement(name = "Pric")
    protected BigDecimal pric;

    /**
     * Gets the value of the cmmdtyBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmmdtyBase() {
        return cmmdtyBase;
    }

    /**
     * Sets the value of the cmmdtyBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmmdtyBase(String value) {
        this.cmmdtyBase = value;
    }

    /**
     * Gets the value of the cmmdtyDtls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmmdtyDtls() {
        return cmmdtyDtls;
    }

    /**
     * Sets the value of the cmmdtyDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmmdtyDtls(String value) {
        this.cmmdtyDtls = value;
    }

    /**
     * Gets the value of the dlvryPnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvryPnt() {
        return dlvryPnt;
    }

    /**
     * Sets the value of the dlvryPnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvryPnt(String value) {
        this.dlvryPnt = value;
    }

    /**
     * Gets the value of the intrcnnctnPnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntrcnnctnPnt() {
        return intrcnnctnPnt;
    }

    /**
     * Sets the value of the intrcnnctnPnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntrcnnctnPnt(String value) {
        this.intrcnnctnPnt = value;
    }

    /**
     * Gets the value of the ldTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdTp() {
        return ldTp;
    }

    /**
     * Sets the value of the ldTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdTp(String value) {
        this.ldTp = value;
    }

    /**
     * Gets the value of the dlvryStartDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public DateAndDateTimeChoice getDlvryStartDtTm() {
        return dlvryStartDtTm;
    }

    /**
     * Sets the value of the dlvryStartDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public void setDlvryStartDtTm(DateAndDateTimeChoice value) {
        this.dlvryStartDtTm = value;
    }

    /**
     * Gets the value of the dlvryEndDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public DateAndDateTimeChoice getDlvryEndDtTm() {
        return dlvryEndDtTm;
    }

    /**
     * Sets the value of the dlvryEndDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndDateTimeChoice }
     *     
     */
    public void setDlvryEndDtTm(DateAndDateTimeChoice value) {
        this.dlvryEndDtTm = value;
    }

    /**
     * Gets the value of the cntrctCpcty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntrctCpcty() {
        return cntrctCpcty;
    }

    /**
     * Sets the value of the cntrctCpcty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntrctCpcty(String value) {
        this.cntrctCpcty = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQty(BigDecimal value) {
        this.qty = value;
    }

    /**
     * Gets the value of the pric property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPric() {
        return pric;
    }

    /**
     * Sets the value of the pric property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPric(BigDecimal value) {
        this.pric = value;
    }

}
