//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 01:49:49 PM CET 
//


package kdpw.xsd.trar_ntf_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kdpw.xsd.trar_ntf_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KDPWDocument_QNAME = new QName("urn:kdpw:xsd:trar.ntf.001.01", "KDPWDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kdpw.xsd.trar_ntf_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KDPWDocument }
     * 
     */
    public KDPWDocument createKDPWDocument() {
        return new KDPWDocument();
    }

    /**
     * Create an instance of {@link ClearingInformation }
     * 
     */
    public ClearingInformation createClearingInformation() {
        return new ClearingInformation();
    }

    /**
     * Create an instance of {@link CollateralInformation }
     * 
     */
    public CollateralInformation createCollateralInformation() {
        return new CollateralInformation();
    }

    /**
     * Create an instance of {@link CommodityTrade }
     * 
     */
    public CommodityTrade createCommodityTrade() {
        return new CommodityTrade();
    }

    /**
     * Create an instance of {@link ContractType }
     * 
     */
    public ContractType createContractType() {
        return new ContractType();
    }

    /**
     * Create an instance of {@link CurrencyAndAmount2 }
     * 
     */
    public CurrencyAndAmount2 createCurrencyAndAmount2() {
        return new CurrencyAndAmount2();
    }

    /**
     * Create an instance of {@link CounterpartyAddressAndSectorDetails }
     * 
     */
    public CounterpartyAddressAndSectorDetails createCounterpartyAddressAndSectorDetails() {
        return new CounterpartyAddressAndSectorDetails();
    }

    /**
     * Create an instance of {@link CounterpartyDetails }
     * 
     */
    public CounterpartyDetails createCounterpartyDetails() {
        return new CounterpartyDetails();
    }

    /**
     * Create an instance of {@link CounterpartyInformation }
     * 
     */
    public CounterpartyInformation createCounterpartyInformation() {
        return new CounterpartyInformation();
    }

    /**
     * Create an instance of {@link DateAndDateTimeChoice }
     * 
     */
    public DateAndDateTimeChoice createDateAndDateTimeChoice() {
        return new DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link Domicile }
     * 
     */
    public Domicile createDomicile() {
        return new Domicile();
    }

    /**
     * Create an instance of {@link FXTrade }
     * 
     */
    public FXTrade createFXTrade() {
        return new FXTrade();
    }

    /**
     * Create an instance of {@link GeneralInformation }
     * 
     */
    public GeneralInformation createGeneralInformation() {
        return new GeneralInformation();
    }

    /**
     * Create an instance of {@link InterestRateTrade }
     * 
     */
    public InterestRateTrade createInterestRateTrade() {
        return new InterestRateTrade();
    }

    /**
     * Create an instance of {@link InstitutionCode }
     * 
     */
    public InstitutionCode createInstitutionCode() {
        return new InstitutionCode();
    }

    /**
     * Create an instance of {@link Linkages }
     * 
     */
    public Linkages createLinkages() {
        return new Linkages();
    }

    /**
     * Create an instance of {@link OptionTrade }
     * 
     */
    public OptionTrade createOptionTrade() {
        return new OptionTrade();
    }

    /**
     * Create an instance of {@link PriceChoice }
     * 
     */
    public PriceChoice createPriceChoice() {
        return new PriceChoice();
    }

    /**
     * Create an instance of {@link Reason }
     * 
     */
    public Reason createReason() {
        return new Reason();
    }

    /**
     * Create an instance of {@link RelatedReference }
     * 
     */
    public RelatedReference createRelatedReference() {
        return new RelatedReference();
    }

    /**
     * Create an instance of {@link RiskMitigation }
     * 
     */
    public RiskMitigation createRiskMitigation() {
        return new RiskMitigation();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link TradeAdditionalInformation }
     * 
     */
    public TradeAdditionalInformation createTradeAdditionalInformation() {
        return new TradeAdditionalInformation();
    }

    /**
     * Create an instance of {@link TradeDetails }
     * 
     */
    public TradeDetails createTradeDetails() {
        return new TradeDetails();
    }

    /**
     * Create an instance of {@link TRInstitutionCode }
     * 
     */
    public TRInstitutionCode createTRInstitutionCode() {
        return new TRInstitutionCode();
    }

    /**
     * Create an instance of {@link TRInstitutionCode2 }
     * 
     */
    public TRInstitutionCode2 createTRInstitutionCode2() {
        return new TRInstitutionCode2();
    }

    /**
     * Create an instance of {@link TradeIdentification }
     * 
     */
    public TradeIdentification createTradeIdentification() {
        return new TradeIdentification();
    }

    /**
     * Create an instance of {@link TradeReference }
     * 
     */
    public TradeReference createTradeReference() {
        return new TradeReference();
    }

    /**
     * Create an instance of {@link UnderlyingDefinition }
     * 
     */
    public UnderlyingDefinition createUnderlyingDefinition() {
        return new UnderlyingDefinition();
    }

    /**
     * Create an instance of {@link ValuationAndCollateralInformation }
     * 
     */
    public ValuationAndCollateralInformation createValuationAndCollateralInformation() {
        return new ValuationAndCollateralInformation();
    }

    /**
     * Create an instance of {@link ValuationInformation }
     * 
     */
    public ValuationInformation createValuationInformation() {
        return new ValuationInformation();
    }

    /**
     * Create an instance of {@link TrarNtf00101 }
     * 
     */
    public TrarNtf00101 createTrarNtf00101() {
        return new TrarNtf00101();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDPWDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:kdpw:xsd:trar.ntf.001.01", name = "KDPWDocument")
    public JAXBElement<KDPWDocument> createKDPWDocument(KDPWDocument value) {
        return new JAXBElement<>(_KDPWDocument_QNAME, KDPWDocument.class, null, value);
    }

}
