//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:33:43 AM CEST 
//


package kdpw.xsd.trar_ins_004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * – Identyfikacja produktu
 * 
 * <p>Java class for ProductIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductIdentification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Txnm" type="{urn:kdpw:xsd:trar.ins.004.02}Max1Text"/&gt;
 *         &lt;element name="PrdctId1" type="{urn:kdpw:xsd:trar.ins.004.02}Max20Text"/&gt;
 *         &lt;element name="PrdctId2" type="{urn:kdpw:xsd:trar.ins.004.02}Max20Text" minOccurs="0"/&gt;
 *         &lt;element name="TechUndrlyg" type="{urn:kdpw:xsd:trar.ins.004.02}Max20Text"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductIdentification", propOrder = {
    "txnm",
    "prdctId1",
    "prdctId2",
    "techUndrlyg"
})
public class ProductIdentification {

    @XmlElement(name = "Txnm", required = true)
    protected String txnm;
    @XmlElement(name = "PrdctId1", required = true)
    protected String prdctId1;
    @XmlElement(name = "PrdctId2")
    protected String prdctId2;
    @XmlElement(name = "TechUndrlyg", required = true)
    protected String techUndrlyg;

    /**
     * Gets the value of the txnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnm() {
        return txnm;
    }

    /**
     * Sets the value of the txnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnm(String value) {
        this.txnm = value;
    }

    /**
     * Gets the value of the prdctId1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrdctId1() {
        return prdctId1;
    }

    /**
     * Sets the value of the prdctId1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrdctId1(String value) {
        this.prdctId1 = value;
    }

    /**
     * Gets the value of the prdctId2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrdctId2() {
        return prdctId2;
    }

    /**
     * Sets the value of the prdctId2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrdctId2(String value) {
        this.prdctId2 = value;
    }

    /**
     * Gets the value of the techUndrlyg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechUndrlyg() {
        return techUndrlyg;
    }

    /**
     * Sets the value of the techUndrlyg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechUndrlyg(String value) {
        this.techUndrlyg = value;
    }

}
