//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:33:44 AM CEST 
//


package kdpw.xsd.trar_ins_005;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Raportowanie zmian danych kontrahenta
 * 
 * <p>Java class for trar.ins.005.02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trar.ins.005.02"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GnlInf" type="{urn:kdpw:xsd:trar.ins.005.02}GeneralInformation"/&gt;
 *         &lt;element name="CtrPtyTRId" type="{urn:kdpw:xsd:trar.ins.005.02}TRInstitutionCode"/&gt;
 *         &lt;element name="CtrPtyAdrAndSctr" type="{urn:kdpw:xsd:trar.ins.005.02}CounterpartyAddressAndSectorDetails" minOccurs="0"/&gt;
 *         &lt;element name="FinNonFinInd" type="{urn:kdpw:xsd:trar.ins.005.02}Max1Text" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trar.ins.005.02", propOrder = {
    "gnlInf",
    "ctrPtyTRId",
    "ctrPtyAdrAndSctr",
    "finNonFinInd"
})
public class TrarIns00502 {

    @XmlElement(name = "GnlInf", required = true)
    protected GeneralInformation gnlInf;
    @XmlElement(name = "CtrPtyTRId", required = true)
    protected TRInstitutionCode ctrPtyTRId;
    @XmlElement(name = "CtrPtyAdrAndSctr")
    protected CounterpartyAddressAndSectorDetails ctrPtyAdrAndSctr;
    @XmlElement(name = "FinNonFinInd")
    protected String finNonFinInd;

    /**
     * Gets the value of the gnlInf property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralInformation }
     *     
     */
    public GeneralInformation getGnlInf() {
        return gnlInf;
    }

    /**
     * Sets the value of the gnlInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralInformation }
     *     
     */
    public void setGnlInf(GeneralInformation value) {
        this.gnlInf = value;
    }

    /**
     * Gets the value of the ctrPtyTRId property.
     * 
     * @return
     *     possible object is
     *     {@link TRInstitutionCode }
     *     
     */
    public TRInstitutionCode getCtrPtyTRId() {
        return ctrPtyTRId;
    }

    /**
     * Sets the value of the ctrPtyTRId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRInstitutionCode }
     *     
     */
    public void setCtrPtyTRId(TRInstitutionCode value) {
        this.ctrPtyTRId = value;
    }

    /**
     * Gets the value of the ctrPtyAdrAndSctr property.
     * 
     * @return
     *     possible object is
     *     {@link CounterpartyAddressAndSectorDetails }
     *     
     */
    public CounterpartyAddressAndSectorDetails getCtrPtyAdrAndSctr() {
        return ctrPtyAdrAndSctr;
    }

    /**
     * Sets the value of the ctrPtyAdrAndSctr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CounterpartyAddressAndSectorDetails }
     *     
     */
    public void setCtrPtyAdrAndSctr(CounterpartyAddressAndSectorDetails value) {
        this.ctrPtyAdrAndSctr = value;
    }

    /**
     * Gets the value of the finNonFinInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinNonFinInd() {
        return finNonFinInd;
    }

    /**
     * Sets the value of the finNonFinInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinNonFinInd(String value) {
        this.finNonFinInd = value;
    }

}
