//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.30 at 11:11:04 AM GMT 
//


package kdpw.xsd.trar_sts_001_02;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Identyfikator przesłanego raportu 
 * 
 * <p>Java class for RelatedReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedReference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PrvsSndrMsgRef" type="{urn:kdpw:xsd:trar.sts.001.02}Max16Text"/&gt;
 *         &lt;element name="CtrPtySd" type="{urn:kdpw:xsd:trar.sts.001.02}Max1Text" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedReference", propOrder = {
    "prvsSndrMsgRef",
    "ctrPtySd"
})
public class RelatedReference {

    @XmlElement(name = "PrvsSndrMsgRef", required = true)
    protected String prvsSndrMsgRef;
    @XmlElement(name = "CtrPtySd")
    protected String ctrPtySd;

    /**
     * Gets the value of the prvsSndrMsgRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrvsSndrMsgRef() {
        return prvsSndrMsgRef;
    }

    /**
     * Sets the value of the prvsSndrMsgRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrvsSndrMsgRef(String value) {
        this.prvsSndrMsgRef = value;
    }

    /**
     * Gets the value of the ctrPtySd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtrPtySd() {
        return ctrPtySd;
    }

    /**
     * Sets the value of the ctrPtySd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtrPtySd(String value) {
        this.ctrPtySd = value;
    }

}
