//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 04:37:17 PM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information related to counterparty identification.
 * 
 * <p>Java class for CounterpartyOther_TR_M complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CounterpartyOther_TR_M"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{urn:kdpw:xsd:trar.ins.001.04}OrganisationIdentification3Choice__1"/&gt;
 *         &lt;element name="Ctry" type="{urn:kdpw:xsd:trar.ins.001.04}CountryCode"/&gt;
 *         &lt;element name="EMIROblgtn" type="{urn:kdpw:xsd:trar.ins.001.04}YesNoIndicator"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CounterpartyOther_TR_M", propOrder = {
    "id",
    "ctry",
    "emirOblgtn"
})
public class CounterpartyOtherTRM {

    @XmlElement(name = "Id", required = true)
    protected OrganisationIdentification3Choice1 id;
    @XmlElement(name = "Ctry", required = true)
    protected String ctry;
    @XmlElement(name = "EMIROblgtn")
    protected boolean emirOblgtn;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationIdentification3Choice1 }
     *     
     */
    public OrganisationIdentification3Choice1 getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationIdentification3Choice1 }
     *     
     */
    public void setId(OrganisationIdentification3Choice1 value) {
        this.id = value;
    }

    /**
     * Gets the value of the ctry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtry() {
        return ctry;
    }

    /**
     * Sets the value of the ctry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtry(String value) {
        this.ctry = value;
    }

    /**
     * Gets the value of the emirOblgtn property.
     * 
     */
    public boolean isEMIROblgtn() {
        return emirOblgtn;
    }

    /**
     * Sets the value of the emirOblgtn property.
     * 
     */
    public void setEMIROblgtn(boolean value) {
        this.emirOblgtn = value;
    }

}
