//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.02 at 10:13:41 AM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Stopy procentowe.
 * 				Sekcja wypełniania/raportowana  dla kontraktów na stopę procentową walutę; jeśli UPI jest raportowane i zawiera wszystkie informacje wskazane poniżej, to ta sekcja nie jest wypełniania /raportowana.
 * 			 
 * 
 * <p>Java class for InterestRateTrade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterestRateTrade"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FxdRateLg1" type="{urn:kdpw:xsd:trar.ins.001.02}Max20Dec5SignedOrDelete" minOccurs="0"/&gt;
 *         &lt;element name="FxdRateLg2" type="{urn:kdpw:xsd:trar.ins.001.02}Max20Dec5SignedOrDelete" minOccurs="0"/&gt;
 *         &lt;element name="FxdRateDayCnt" type="{urn:kdpw:xsd:trar.ins.001.02}Max10TextOrDelete" minOccurs="0"/&gt;
 *         &lt;element name="FxdLgPmtFrqcy" type="{urn:kdpw:xsd:trar.ins.001.02}Max10TextOrDelete" minOccurs="0"/&gt;
 *         &lt;element name="FltgLgPmtFrqcy" type="{urn:kdpw:xsd:trar.ins.001.02}Max10TextOrDelete" minOccurs="0"/&gt;
 *         &lt;element name="FltgRateRstFrqcy" type="{urn:kdpw:xsd:trar.ins.001.02}Max10TextOrDelete" minOccurs="0"/&gt;
 *         &lt;element name="FltgRateLg1" type="{urn:kdpw:xsd:trar.ins.001.02}Max20TextOrDelete" minOccurs="0"/&gt;
 *         &lt;element name="FltgRateLg2" type="{urn:kdpw:xsd:trar.ins.001.02}Max20TextOrDelete" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DeltnInd" type="{urn:kdpw:xsd:trar.ins.001.02}YesNoIndicator" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterestRateTrade", propOrder = {
    "fxdRateLg1",
    "fxdRateLg2",
    "fxdRateDayCnt",
    "fxdLgPmtFrqcy",
    "fltgLgPmtFrqcy",
    "fltgRateRstFrqcy",
    "fltgRateLg1",
    "fltgRateLg2"
})
public class InterestRateTrade {

    @XmlElement(name = "FxdRateLg1")
    protected Max20Dec5SignedOrDelete fxdRateLg1;
    @XmlElement(name = "FxdRateLg2")
    protected Max20Dec5SignedOrDelete fxdRateLg2;
    @XmlElement(name = "FxdRateDayCnt")
    protected Max10TextOrDelete fxdRateDayCnt;
    @XmlElement(name = "FxdLgPmtFrqcy")
    protected Max10TextOrDelete fxdLgPmtFrqcy;
    @XmlElement(name = "FltgLgPmtFrqcy")
    protected Max10TextOrDelete fltgLgPmtFrqcy;
    @XmlElement(name = "FltgRateRstFrqcy")
    protected Max10TextOrDelete fltgRateRstFrqcy;
    @XmlElement(name = "FltgRateLg1")
    protected Max20TextOrDelete fltgRateLg1;
    @XmlElement(name = "FltgRateLg2")
    protected Max20TextOrDelete fltgRateLg2;
    @XmlAttribute(name = "DeltnInd")
    protected YesNoIndicator deltnInd;

    /**
     * Gets the value of the fxdRateLg1 property.
     * 
     * @return
     *     possible object is
     *     {@link Max20Dec5SignedOrDelete }
     *     
     */
    public Max20Dec5SignedOrDelete getFxdRateLg1() {
        return fxdRateLg1;
    }

    /**
     * Sets the value of the fxdRateLg1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max20Dec5SignedOrDelete }
     *     
     */
    public void setFxdRateLg1(Max20Dec5SignedOrDelete value) {
        this.fxdRateLg1 = value;
    }

    /**
     * Gets the value of the fxdRateLg2 property.
     * 
     * @return
     *     possible object is
     *     {@link Max20Dec5SignedOrDelete }
     *     
     */
    public Max20Dec5SignedOrDelete getFxdRateLg2() {
        return fxdRateLg2;
    }

    /**
     * Sets the value of the fxdRateLg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max20Dec5SignedOrDelete }
     *     
     */
    public void setFxdRateLg2(Max20Dec5SignedOrDelete value) {
        this.fxdRateLg2 = value;
    }

    /**
     * Gets the value of the fxdRateDayCnt property.
     * 
     * @return
     *     possible object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public Max10TextOrDelete getFxdRateDayCnt() {
        return fxdRateDayCnt;
    }

    /**
     * Sets the value of the fxdRateDayCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public void setFxdRateDayCnt(Max10TextOrDelete value) {
        this.fxdRateDayCnt = value;
    }

    /**
     * Gets the value of the fxdLgPmtFrqcy property.
     * 
     * @return
     *     possible object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public Max10TextOrDelete getFxdLgPmtFrqcy() {
        return fxdLgPmtFrqcy;
    }

    /**
     * Sets the value of the fxdLgPmtFrqcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public void setFxdLgPmtFrqcy(Max10TextOrDelete value) {
        this.fxdLgPmtFrqcy = value;
    }

    /**
     * Gets the value of the fltgLgPmtFrqcy property.
     * 
     * @return
     *     possible object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public Max10TextOrDelete getFltgLgPmtFrqcy() {
        return fltgLgPmtFrqcy;
    }

    /**
     * Sets the value of the fltgLgPmtFrqcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public void setFltgLgPmtFrqcy(Max10TextOrDelete value) {
        this.fltgLgPmtFrqcy = value;
    }

    /**
     * Gets the value of the fltgRateRstFrqcy property.
     * 
     * @return
     *     possible object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public Max10TextOrDelete getFltgRateRstFrqcy() {
        return fltgRateRstFrqcy;
    }

    /**
     * Sets the value of the fltgRateRstFrqcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max10TextOrDelete }
     *     
     */
    public void setFltgRateRstFrqcy(Max10TextOrDelete value) {
        this.fltgRateRstFrqcy = value;
    }

    /**
     * Gets the value of the fltgRateLg1 property.
     * 
     * @return
     *     possible object is
     *     {@link Max20TextOrDelete }
     *     
     */
    public Max20TextOrDelete getFltgRateLg1() {
        return fltgRateLg1;
    }

    /**
     * Sets the value of the fltgRateLg1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max20TextOrDelete }
     *     
     */
    public void setFltgRateLg1(Max20TextOrDelete value) {
        this.fltgRateLg1 = value;
    }

    /**
     * Gets the value of the fltgRateLg2 property.
     * 
     * @return
     *     possible object is
     *     {@link Max20TextOrDelete }
     *     
     */
    public Max20TextOrDelete getFltgRateLg2() {
        return fltgRateLg2;
    }

    /**
     * Sets the value of the fltgRateLg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max20TextOrDelete }
     *     
     */
    public void setFltgRateLg2(Max20TextOrDelete value) {
        this.fltgRateLg2 = value;
    }

    /**
     * Gets the value of the deltnInd property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoIndicator }
     *     
     */
    public YesNoIndicator getDeltnInd() {
        return deltnInd;
    }

    /**
     * Sets the value of the deltnInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoIndicator }
     *     
     */
    public void setDeltnInd(YesNoIndicator value) {
        this.deltnInd = value;
    }

}
