//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.29 at 02:25:35 PM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data set related to MIFIR regulation requirements.
 * 
 * <p>Java class for MIFIRInstrumentOtherData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MIFIRInstrumentOtherData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FullNm" type="{urn:kdpw:xsd:trar.ins.001.04}ESMA_AlphaNumericAdditionalCharactersMax350_Pattern"/&gt;
 *         &lt;element name="Swp" type="{urn:kdpw:xsd:trar.ins.001.04}SwapLegIdentification2__1" minOccurs="0"/&gt;
 *         &lt;element name="AsstClssSpcfcAttrbts" type="{urn:kdpw:xsd:trar.ins.001.04}AssetClassAttributes1Choice__1" minOccurs="0"/&gt;
 *         &lt;element name="StrkPriceCcy" type="{urn:kdpw:xsd:trar.ins.001.04}ActiveCurrencyCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MIFIRInstrumentOtherData", propOrder = {
    "fullNm",
    "swp",
    "asstClssSpcfcAttrbts",
    "strkPriceCcy"
})
public class MIFIRInstrumentOtherData {

    @XmlElement(name = "FullNm", required = true)
    protected String fullNm;
    @XmlElement(name = "Swp")
    protected SwapLegIdentification21 swp;
    @XmlElement(name = "AsstClssSpcfcAttrbts")
    protected AssetClassAttributes1Choice1 asstClssSpcfcAttrbts;
    @XmlElement(name = "StrkPriceCcy")
    protected String strkPriceCcy;

    /**
     * Gets the value of the fullNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullNm() {
        return fullNm;
    }

    /**
     * Sets the value of the fullNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullNm(String value) {
        this.fullNm = value;
    }

    /**
     * Gets the value of the swp property.
     * 
     * @return
     *     possible object is
     *     {@link SwapLegIdentification21 }
     *     
     */
    public SwapLegIdentification21 getSwp() {
        return swp;
    }

    /**
     * Sets the value of the swp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwapLegIdentification21 }
     *     
     */
    public void setSwp(SwapLegIdentification21 value) {
        this.swp = value;
    }

    /**
     * Gets the value of the asstClssSpcfcAttrbts property.
     * 
     * @return
     *     possible object is
     *     {@link AssetClassAttributes1Choice1 }
     *     
     */
    public AssetClassAttributes1Choice1 getAsstClssSpcfcAttrbts() {
        return asstClssSpcfcAttrbts;
    }

    /**
     * Sets the value of the asstClssSpcfcAttrbts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetClassAttributes1Choice1 }
     *     
     */
    public void setAsstClssSpcfcAttrbts(AssetClassAttributes1Choice1 value) {
        this.asstClssSpcfcAttrbts = value;
    }

    /**
     * Gets the value of the strkPriceCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrkPriceCcy() {
        return strkPriceCcy;
    }

    /**
     * Sets the value of the strkPriceCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrkPriceCcy(String value) {
        this.strkPriceCcy = value;
    }

}
