//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.14 at 01:33:12 PM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data set related to MIFIR regulation requirements.
 * 
 * <p>Java class for MIFIRInstrumentOtherData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MIFIRInstrumentOtherData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SwpInOutInd" type="{urn:kdpw:xsd:trar.ins.001.03}YesNoIndicator" minOccurs="0"/&gt;
 *         &lt;element name="AsstClssSpcfcAttrbts" type="{urn:kdpw:xsd:trar.ins.001.03}AssetClassAttributes1Choice__1" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MIFIRInstrumentOtherData", propOrder = {
    "swpInOutInd",
    "asstClssSpcfcAttrbts"
})
public class MIFIRInstrumentOtherData {

    @XmlElement(name = "SwpInOutInd")
    protected Boolean swpInOutInd;
    @XmlElement(name = "AsstClssSpcfcAttrbts")
    protected AssetClassAttributes1Choice1 asstClssSpcfcAttrbts;

    /**
     * Gets the value of the swpInOutInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSwpInOutInd() {
        return swpInOutInd;
    }

    /**
     * Sets the value of the swpInOutInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSwpInOutInd(Boolean value) {
        this.swpInOutInd = value;
    }

    /**
     * Gets the value of the asstClssSpcfcAttrbts property.
     * 
     * @return
     *     possible object is
     *     {@link AssetClassAttributes1Choice1 }
     *     
     */
    public AssetClassAttributes1Choice1 getAsstClssSpcfcAttrbts() {
        return asstClssSpcfcAttrbts;
    }

    /**
     * Sets the value of the asstClssSpcfcAttrbts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetClassAttributes1Choice1 }
     *     
     */
    public void setAsstClssSpcfcAttrbts(AssetClassAttributes1Choice1 value) {
        this.asstClssSpcfcAttrbts = value;
    }

}
