//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 11:10:30 AM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kdpw.xsd.trar_ins_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KDPWDocument_QNAME = new QName("urn:kdpw:xsd:trar.ins.001.03", "KDPWDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kdpw.xsd.trar_ins_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KDPWDocument }
     * 
     */
    public KDPWDocument createKDPWDocument() {
        return new KDPWDocument();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAnd20Amount }
     * 
     */
    public ActiveCurrencyAnd20Amount createActiveCurrencyAnd20Amount() {
        return new ActiveCurrencyAnd20Amount();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAnd20AmountN }
     * 
     */
    public ActiveCurrencyAnd20AmountN createActiveCurrencyAnd20AmountN() {
        return new ActiveCurrencyAnd20AmountN();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAnd20Amount }
     * 
     */
    public ActiveOrHistoricCurrencyAnd20Amount createActiveOrHistoricCurrencyAnd20Amount() {
        return new ActiveOrHistoricCurrencyAnd20Amount();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAnd20AmountNegative }
     * 
     */
    public ActiveOrHistoricCurrencyAnd20AmountNegative createActiveOrHistoricCurrencyAnd20AmountNegative() {
        return new ActiveOrHistoricCurrencyAnd20AmountNegative();
    }

    /**
     * Create an instance of {@link AmountAndDirection54 }
     * 
     */
    public AmountAndDirection54 createAmountAndDirection54() {
        return new AmountAndDirection54();
    }

    /**
     * Create an instance of {@link AssetClassAttributes1Choice1 }
     * 
     */
    public AssetClassAttributes1Choice1 createAssetClassAttributes1Choice1() {
        return new AssetClassAttributes1Choice1();
    }

    /**
     * Create an instance of {@link CommodityTrade }
     * 
     */
    public CommodityTrade createCommodityTrade() {
        return new CommodityTrade();
    }

    /**
     * Create an instance of {@link CommodityTradeM }
     * 
     */
    public CommodityTradeM createCommodityTradeM() {
        return new CommodityTradeM();
    }

    /**
     * Create an instance of {@link CommodityTradeR }
     * 
     */
    public CommodityTradeR createCommodityTradeR() {
        return new CommodityTradeR();
    }

    /**
     * Create an instance of {@link CommonTradeDataReport133 }
     * 
     */
    public CommonTradeDataReport133 createCommonTradeDataReport133() {
        return new CommonTradeDataReport133();
    }

    /**
     * Create an instance of {@link CommonTradeDataReport134 }
     * 
     */
    public CommonTradeDataReport134 createCommonTradeDataReport134() {
        return new CommonTradeDataReport134();
    }

    /**
     * Create an instance of {@link CommonTradeDataReport136 }
     * 
     */
    public CommonTradeDataReport136 createCommonTradeDataReport136() {
        return new CommonTradeDataReport136();
    }

    /**
     * Create an instance of {@link CommonTradeDataReport161 }
     * 
     */
    public CommonTradeDataReport161 createCommonTradeDataReport161() {
        return new CommonTradeDataReport161();
    }

    /**
     * Create an instance of {@link CommonTradeDataReport171 }
     * 
     */
    public CommonTradeDataReport171 createCommonTradeDataReport171() {
        return new CommonTradeDataReport171();
    }

    /**
     * Create an instance of {@link CommonTradeDataReportTRPN }
     * 
     */
    public CommonTradeDataReportTRPN createCommonTradeDataReportTRPN() {
        return new CommonTradeDataReportTRPN();
    }

    /**
     * Create an instance of {@link CommonTradeDataReport172 }
     * 
     */
    public CommonTradeDataReport172 createCommonTradeDataReport172() {
        return new CommonTradeDataReport172();
    }

    /**
     * Create an instance of {@link CommonTradeDataReportTRR }
     * 
     */
    public CommonTradeDataReportTRR createCommonTradeDataReportTRR() {
        return new CommonTradeDataReportTRR();
    }

    /**
     * Create an instance of {@link CommonTradeDataReportTRPR }
     * 
     */
    public CommonTradeDataReportTRPR createCommonTradeDataReportTRPR() {
        return new CommonTradeDataReportTRPR();
    }

    /**
     * Create an instance of {@link ContractDetailsTRM }
     * 
     */
    public ContractDetailsTRM createContractDetailsTRM() {
        return new ContractDetailsTRM();
    }

    /**
     * Create an instance of {@link ContractDetailsTRR }
     * 
     */
    public ContractDetailsTRR createContractDetailsTRR() {
        return new ContractDetailsTRR();
    }

    /**
     * Create an instance of {@link ContractDetailsTRN }
     * 
     */
    public ContractDetailsTRN createContractDetailsTRN() {
        return new ContractDetailsTRN();
    }

    /**
     * Create an instance of {@link ContractType31 }
     * 
     */
    public ContractType31 createContractType31() {
        return new ContractType31();
    }

    /**
     * Create an instance of {@link ContractType32 }
     * 
     */
    public ContractType32 createContractType32() {
        return new ContractType32();
    }

    /**
     * Create an instance of {@link ContractType42 }
     * 
     */
    public ContractType42 createContractType42() {
        return new ContractType42();
    }

    /**
     * Create an instance of {@link ContractType42R }
     * 
     */
    public ContractType42R createContractType42R() {
        return new ContractType42R();
    }

    /**
     * Create an instance of {@link ContractValuationDataTRN }
     * 
     */
    public ContractValuationDataTRN createContractValuationDataTRN() {
        return new ContractValuationDataTRN();
    }

    /**
     * Create an instance of {@link ContractValuationDataTR }
     * 
     */
    public ContractValuationDataTR createContractValuationDataTR() {
        return new ContractValuationDataTR();
    }

    /**
     * Create an instance of {@link ContractValuationDataTRV }
     * 
     */
    public ContractValuationDataTRV createContractValuationDataTRV() {
        return new ContractValuationDataTRV();
    }

    /**
     * Create an instance of {@link CounterpartyTRR }
     * 
     */
    public CounterpartyTRR createCounterpartyTRR() {
        return new CounterpartyTRR();
    }

    /**
     * Create an instance of {@link CounterpartyTRPR }
     * 
     */
    public CounterpartyTRPR createCounterpartyTRPR() {
        return new CounterpartyTRPR();
    }

    /**
     * Create an instance of {@link CounterpartyTRM }
     * 
     */
    public CounterpartyTRM createCounterpartyTRM() {
        return new CounterpartyTRM();
    }

    /**
     * Create an instance of {@link CounterpartyTRN }
     * 
     */
    public CounterpartyTRN createCounterpartyTRN() {
        return new CounterpartyTRN();
    }

    /**
     * Create an instance of {@link CounterpartyTRPN }
     * 
     */
    public CounterpartyTRPN createCounterpartyTRPN() {
        return new CounterpartyTRPN();
    }

    /**
     * Create an instance of {@link CounterpartyTRZ }
     * 
     */
    public CounterpartyTRZ createCounterpartyTRZ() {
        return new CounterpartyTRZ();
    }

    /**
     * Create an instance of {@link CounterpartyOtherTR }
     * 
     */
    public CounterpartyOtherTR createCounterpartyOtherTR() {
        return new CounterpartyOtherTR();
    }

    /**
     * Create an instance of {@link CounterpartyOtherTRR }
     * 
     */
    public CounterpartyOtherTRR createCounterpartyOtherTRR() {
        return new CounterpartyOtherTRR();
    }

    /**
     * Create an instance of {@link CounterpartyOtherTRM }
     * 
     */
    public CounterpartyOtherTRM createCounterpartyOtherTRM() {
        return new CounterpartyOtherTRM();
    }

    /**
     * Create an instance of {@link CounterpartyOtherTRN }
     * 
     */
    public CounterpartyOtherTRN createCounterpartyOtherTRN() {
        return new CounterpartyOtherTRN();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRM }
     * 
     */
    public CounterpartySpecificDataTRM createCounterpartySpecificDataTRM() {
        return new CounterpartySpecificDataTRM();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRR }
     * 
     */
    public CounterpartySpecificDataTRR createCounterpartySpecificDataTRR() {
        return new CounterpartySpecificDataTRR();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRPR }
     * 
     */
    public CounterpartySpecificDataTRPR createCounterpartySpecificDataTRPR() {
        return new CounterpartySpecificDataTRPR();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRN }
     * 
     */
    public CounterpartySpecificDataTRN createCounterpartySpecificDataTRN() {
        return new CounterpartySpecificDataTRN();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRPC }
     * 
     */
    public CounterpartySpecificDataTRPC createCounterpartySpecificDataTRPC() {
        return new CounterpartySpecificDataTRPC();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRPN }
     * 
     */
    public CounterpartySpecificDataTRPN createCounterpartySpecificDataTRPN() {
        return new CounterpartySpecificDataTRPN();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRV }
     * 
     */
    public CounterpartySpecificDataTRV createCounterpartySpecificDataTRV() {
        return new CounterpartySpecificDataTRV();
    }

    /**
     * Create an instance of {@link CounterpartySpecificDataTRZ }
     * 
     */
    public CounterpartySpecificDataTRZ createCounterpartySpecificDataTRZ() {
        return new CounterpartySpecificDataTRZ();
    }

    /**
     * Create an instance of {@link CreditDerivativeTR }
     * 
     */
    public CreditDerivativeTR createCreditDerivativeTR() {
        return new CreditDerivativeTR();
    }

    /**
     * Create an instance of {@link CreditDerivativeTRM }
     * 
     */
    public CreditDerivativeTRM createCreditDerivativeTRM() {
        return new CreditDerivativeTRM();
    }

    /**
     * Create an instance of {@link CreditDerivativeTRR }
     * 
     */
    public CreditDerivativeTRR createCreditDerivativeTRR() {
        return new CreditDerivativeTRR();
    }

    /**
     * Create an instance of {@link CurrencyExchange101 }
     * 
     */
    public CurrencyExchange101 createCurrencyExchange101() {
        return new CurrencyExchange101();
    }

    /**
     * Create an instance of {@link DeliveryInterconnectionPoint1Choice }
     * 
     */
    public DeliveryInterconnectionPoint1Choice createDeliveryInterconnectionPoint1Choice() {
        return new DeliveryInterconnectionPoint1Choice();
    }

    /**
     * Create an instance of {@link DateAndDateTimeChoice }
     * 
     */
    public DateAndDateTimeChoice createDateAndDateTimeChoice() {
        return new DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link DerivativeForeignExchange2 }
     * 
     */
    public DerivativeForeignExchange2 createDerivativeForeignExchange2() {
        return new DerivativeForeignExchange2();
    }

    /**
     * Create an instance of {@link DerivativeInterest2 }
     * 
     */
    public DerivativeInterest2 createDerivativeInterest2() {
        return new DerivativeInterest2();
    }

    /**
     * Create an instance of {@link EnergyDeliveryAttribute31 }
     * 
     */
    public EnergyDeliveryAttribute31 createEnergyDeliveryAttribute31() {
        return new EnergyDeliveryAttribute31();
    }

    /**
     * Create an instance of {@link ExchangeRateBasis1 }
     * 
     */
    public ExchangeRateBasis1 createExchangeRateBasis1() {
        return new ExchangeRateBasis1();
    }

    /**
     * Create an instance of {@link ExecutingParty1Choice1 }
     * 
     */
    public ExecutingParty1Choice1 createExecutingParty1Choice1() {
        return new ExecutingParty1Choice1();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantity24Choice2 }
     * 
     */
    public FinancialInstrumentQuantity24Choice2 createFinancialInstrumentQuantity24Choice2() {
        return new FinancialInstrumentQuantity24Choice2();
    }

    /**
     * Create an instance of {@link FixedRateTR }
     * 
     */
    public FixedRateTR createFixedRateTR() {
        return new FixedRateTR();
    }

    /**
     * Create an instance of {@link FloatingRateTR }
     * 
     */
    public FloatingRateTR createFloatingRateTR() {
        return new FloatingRateTR();
    }

    /**
     * Create an instance of {@link FloatingRateIdentification1Choice }
     * 
     */
    public FloatingRateIdentification1Choice createFloatingRateIdentification1Choice() {
        return new FloatingRateIdentification1Choice();
    }

    /**
     * Create an instance of {@link GeneralInformation }
     * 
     */
    public GeneralInformation createGeneralInformation() {
        return new GeneralInformation();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification11 }
     * 
     */
    public GenericPersonIdentification11 createGenericPersonIdentification11() {
        return new GenericPersonIdentification11();
    }

    /**
     * Create an instance of {@link InterestRate11Choice1 }
     * 
     */
    public InterestRate11Choice1 createInterestRate11Choice1() {
        return new InterestRate11Choice1();
    }

    /**
     * Create an instance of {@link InterestRateLegs41 }
     * 
     */
    public InterestRateLegs41 createInterestRateLegs41() {
        return new InterestRateLegs41();
    }

    /**
     * Create an instance of {@link InvestmentParty1Choice1 }
     * 
     */
    public InvestmentParty1Choice1 createInvestmentParty1Choice1() {
        return new InvestmentParty1Choice1();
    }

    /**
     * Create an instance of {@link MasterAgreementTR }
     * 
     */
    public MasterAgreementTR createMasterAgreementTR() {
        return new MasterAgreementTR();
    }

    /**
     * Create an instance of {@link MIFIRInstrumentData }
     * 
     */
    public MIFIRInstrumentData createMIFIRInstrumentData() {
        return new MIFIRInstrumentData();
    }

    /**
     * Create an instance of {@link MIFIRInstrumentOtherData }
     * 
     */
    public MIFIRInstrumentOtherData createMIFIRInstrumentOtherData() {
        return new MIFIRInstrumentOtherData();
    }

    /**
     * Create an instance of {@link MIFIRReportingData }
     * 
     */
    public MIFIRReportingData createMIFIRReportingData() {
        return new MIFIRReportingData();
    }

    /**
     * Create an instance of {@link MIFIRTransactionData }
     * 
     */
    public MIFIRTransactionData createMIFIRTransactionData() {
        return new MIFIRTransactionData();
    }

    /**
     * Create an instance of {@link OptionTR }
     * 
     */
    public OptionTR createOptionTR() {
        return new OptionTR();
    }

    /**
     * Create an instance of {@link OptionTRM }
     * 
     */
    public OptionTRM createOptionTRM() {
        return new OptionTRM();
    }

    /**
     * Create an instance of {@link OptionTRR }
     * 
     */
    public OptionTRR createOptionTRR() {
        return new OptionTRR();
    }

    /**
     * Create an instance of {@link OrganisationIdentification3Choice1 }
     * 
     */
    public OrganisationIdentification3Choice1 createOrganisationIdentification3Choice1() {
        return new OrganisationIdentification3Choice1();
    }

    /**
     * Create an instance of {@link PartyIdentificationEMIRD }
     * 
     */
    public PartyIdentificationEMIRD createPartyIdentificationEMIRD() {
        return new PartyIdentificationEMIRD();
    }

    /**
     * Create an instance of {@link PartyIdentificationEMIR }
     * 
     */
    public PartyIdentificationEMIR createPartyIdentificationEMIR() {
        return new PartyIdentificationEMIR();
    }

    /**
     * Create an instance of {@link Period101 }
     * 
     */
    public Period101 createPeriod101() {
        return new Period101();
    }

    /**
     * Create an instance of {@link PersonIdentification101 }
     * 
     */
    public PersonIdentification101 createPersonIdentification101() {
        return new PersonIdentification101();
    }

    /**
     * Create an instance of {@link PersonIdentification121 }
     * 
     */
    public PersonIdentification121 createPersonIdentification121() {
        return new PersonIdentification121();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice1 }
     * 
     */
    public PersonIdentificationSchemeName1Choice1 createPersonIdentificationSchemeName1Choice1() {
        return new PersonIdentificationSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link PersonOrOrganisation1ChoiceEMIR }
     * 
     */
    public PersonOrOrganisation1ChoiceEMIR createPersonOrOrganisation1ChoiceEMIR() {
        return new PersonOrOrganisation1ChoiceEMIR();
    }

    /**
     * Create an instance of {@link PersonOrOrganisation2ChoiceTR }
     * 
     */
    public PersonOrOrganisation2ChoiceTR createPersonOrOrganisation2ChoiceTR() {
        return new PersonOrOrganisation2ChoiceTR();
    }

    /**
     * Create an instance of {@link ProductClassification1Choice }
     * 
     */
    public ProductClassification1Choice createProductClassification1Choice() {
        return new ProductClassification1Choice();
    }

    /**
     * Create an instance of {@link ReferenceParty }
     * 
     */
    public ReferenceParty createReferenceParty() {
        return new ReferenceParty();
    }

    /**
     * Create an instance of {@link SecurityIdentification18Choice1 }
     * 
     */
    public SecurityIdentification18Choice1 createSecurityIdentification18Choice1() {
        return new SecurityIdentification18Choice1();
    }

    /**
     * Create an instance of {@link SecurityIdentification19Choice2 }
     * 
     */
    public SecurityIdentification19Choice2 createSecurityIdentification19Choice2() {
        return new SecurityIdentification19Choice2();
    }

    /**
     * Create an instance of {@link SecurityIdentification20Choice }
     * 
     */
    public SecurityIdentification20Choice createSecurityIdentification20Choice() {
        return new SecurityIdentification20Choice();
    }

    /**
     * Create an instance of {@link SecuritiesTransactionIndicator21 }
     * 
     */
    public SecuritiesTransactionIndicator21 createSecuritiesTransactionIndicator21() {
        return new SecuritiesTransactionIndicator21();
    }

    /**
     * Create an instance of {@link SecuritiesTransactionPrice7ChoiceTR }
     * 
     */
    public SecuritiesTransactionPrice7ChoiceTR createSecuritiesTransactionPrice7ChoiceTR() {
        return new SecuritiesTransactionPrice7ChoiceTR();
    }

    /**
     * Create an instance of {@link SecuritiesTransactionPrice7ChoiceTRO }
     * 
     */
    public SecuritiesTransactionPrice7ChoiceTRO createSecuritiesTransactionPrice7ChoiceTRO() {
        return new SecuritiesTransactionPrice7ChoiceTRO();
    }

    /**
     * Create an instance of {@link SecuritiesTransactionTransmission2 }
     * 
     */
    public SecuritiesTransactionTransmission2 createSecuritiesTransactionTransmission2() {
        return new SecuritiesTransactionTransmission2();
    }

    /**
     * Create an instance of {@link TradeClearingTR }
     * 
     */
    public TradeClearingTR createTradeClearingTR() {
        return new TradeClearingTR();
    }

    /**
     * Create an instance of {@link TradeClearingTRM }
     * 
     */
    public TradeClearingTRM createTradeClearingTRM() {
        return new TradeClearingTRM();
    }

    /**
     * Create an instance of {@link TradeClearingTRR }
     * 
     */
    public TradeClearingTRR createTradeClearingTRR() {
        return new TradeClearingTRR();
    }

    /**
     * Create an instance of {@link TradeCollateralReportTRN }
     * 
     */
    public TradeCollateralReportTRN createTradeCollateralReportTRN() {
        return new TradeCollateralReportTRN();
    }

    /**
     * Create an instance of {@link TradeCollateralReportTRPC }
     * 
     */
    public TradeCollateralReportTRPC createTradeCollateralReportTRPC() {
        return new TradeCollateralReportTRPC();
    }

    /**
     * Create an instance of {@link TradeCollateralReportTRV }
     * 
     */
    public TradeCollateralReportTRV createTradeCollateralReportTRV() {
        return new TradeCollateralReportTRV();
    }

    /**
     * Create an instance of {@link TradeConfirmationTR }
     * 
     */
    public TradeConfirmationTR createTradeConfirmationTR() {
        return new TradeConfirmationTR();
    }

    /**
     * Create an instance of {@link TradeConfirmationTRPN }
     * 
     */
    public TradeConfirmationTRPN createTradeConfirmationTRPN() {
        return new TradeConfirmationTRPN();
    }

    /**
     * Create an instance of {@link TradeNewPositionTR }
     * 
     */
    public TradeNewPositionTR createTradeNewPositionTR() {
        return new TradeNewPositionTR();
    }

    /**
     * Create an instance of {@link TradeNewTransactionTR }
     * 
     */
    public TradeNewTransactionTR createTradeNewTransactionTR() {
        return new TradeNewTransactionTR();
    }

    /**
     * Create an instance of {@link TradePositionComponentTR }
     * 
     */
    public TradePositionComponentTR createTradePositionComponentTR() {
        return new TradePositionComponentTR();
    }

    /**
     * Create an instance of {@link TradePositionCorrectionTR }
     * 
     */
    public TradePositionCorrectionTR createTradePositionCorrectionTR() {
        return new TradePositionCorrectionTR();
    }

    /**
     * Create an instance of {@link TradePositionEarlyTerminationTR }
     * 
     */
    public TradePositionEarlyTerminationTR createTradePositionEarlyTerminationTR() {
        return new TradePositionEarlyTerminationTR();
    }

    /**
     * Create an instance of {@link TradePositionErrorTR }
     * 
     */
    public TradePositionErrorTR createTradePositionErrorTR() {
        return new TradePositionErrorTR();
    }

    /**
     * Create an instance of {@link TradePositionModificationTR }
     * 
     */
    public TradePositionModificationTR createTradePositionModificationTR() {
        return new TradePositionModificationTR();
    }

    /**
     * Create an instance of {@link TradePositionReportChoiceTR }
     * 
     */
    public TradePositionReportChoiceTR createTradePositionReportChoiceTR() {
        return new TradePositionReportChoiceTR();
    }

    /**
     * Create an instance of {@link TradePositionValuationUpdateTR }
     * 
     */
    public TradePositionValuationUpdateTR createTradePositionValuationUpdateTR() {
        return new TradePositionValuationUpdateTR();
    }

    /**
     * Create an instance of {@link TradeReportChoiceTR }
     * 
     */
    public TradeReportChoiceTR createTradeReportChoiceTR() {
        return new TradeReportChoiceTR();
    }

    /**
     * Create an instance of {@link TradeTransactionCorrectionTR }
     * 
     */
    public TradeTransactionCorrectionTR createTradeTransactionCorrectionTR() {
        return new TradeTransactionCorrectionTR();
    }

    /**
     * Create an instance of {@link TradeTransactionEarlyTerminationTR }
     * 
     */
    public TradeTransactionEarlyTerminationTR createTradeTransactionEarlyTerminationTR() {
        return new TradeTransactionEarlyTerminationTR();
    }

    /**
     * Create an instance of {@link TradeTransactionErrorTR }
     * 
     */
    public TradeTransactionErrorTR createTradeTransactionErrorTR() {
        return new TradeTransactionErrorTR();
    }

    /**
     * Create an instance of {@link TradeTransaction101 }
     * 
     */
    public TradeTransaction101 createTradeTransaction101() {
        return new TradeTransaction101();
    }

    /**
     * Create an instance of {@link TradeTransaction102 }
     * 
     */
    public TradeTransaction102 createTradeTransaction102() {
        return new TradeTransaction102();
    }

    /**
     * Create an instance of {@link TradeTransaction113 }
     * 
     */
    public TradeTransaction113 createTradeTransaction113() {
        return new TradeTransaction113();
    }

    /**
     * Create an instance of {@link TradeTransaction114 }
     * 
     */
    public TradeTransaction114 createTradeTransaction114() {
        return new TradeTransaction114();
    }

    /**
     * Create an instance of {@link TradeTransaction116 }
     * 
     */
    public TradeTransaction116 createTradeTransaction116() {
        return new TradeTransaction116();
    }

    /**
     * Create an instance of {@link TradeTransaction121 }
     * 
     */
    public TradeTransaction121 createTradeTransaction121() {
        return new TradeTransaction121();
    }

    /**
     * Create an instance of {@link TradeTransaction131 }
     * 
     */
    public TradeTransaction131 createTradeTransaction131() {
        return new TradeTransaction131();
    }

    /**
     * Create an instance of {@link TradeTransactionTRM }
     * 
     */
    public TradeTransactionTRM createTradeTransactionTRM() {
        return new TradeTransactionTRM();
    }

    /**
     * Create an instance of {@link TradeTransactionTRPN }
     * 
     */
    public TradeTransactionTRPN createTradeTransactionTRPN() {
        return new TradeTransactionTRPN();
    }

    /**
     * Create an instance of {@link TradeTransactionTRPR }
     * 
     */
    public TradeTransactionTRPR createTradeTransactionTRPR() {
        return new TradeTransactionTRPR();
    }

    /**
     * Create an instance of {@link TradeTransactionCompressionTR }
     * 
     */
    public TradeTransactionCompressionTR createTradeTransactionCompressionTR() {
        return new TradeTransactionCompressionTR();
    }

    /**
     * Create an instance of {@link TradeTransactionModificationTR }
     * 
     */
    public TradeTransactionModificationTR createTradeTransactionModificationTR() {
        return new TradeTransactionModificationTR();
    }

    /**
     * Create an instance of {@link TradeTransactionReportChoiceTR }
     * 
     */
    public TradeTransactionReportChoiceTR createTradeTransactionReportChoiceTR() {
        return new TradeTransactionReportChoiceTR();
    }

    /**
     * Create an instance of {@link TradeTransactionValuationUpdateTR }
     * 
     */
    public TradeTransactionValuationUpdateTR createTradeTransactionValuationUpdateTR() {
        return new TradeTransactionValuationUpdateTR();
    }

    /**
     * Create an instance of {@link TrarIns00103 }
     * 
     */
    public TrarIns00103 createTrarIns00103() {
        return new TrarIns00103();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDPWDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:kdpw:xsd:trar.ins.001.03", name = "KDPWDocument")
    public JAXBElement<KDPWDocument> createKDPWDocument(KDPWDocument value) {
        return new JAXBElement<KDPWDocument>(_KDPWDocument_QNAME, KDPWDocument.class, null, value);
    }

}
