//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 11:10:30 AM CEST 
//


package kdpw.xsd.trar_ins_001;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Set of elements used to identify an account owner and the associated decision maker.
 * 
 * <p>Java class for PartyIdentification_EMIR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyIdentification_EMIR"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AcctOwnr" type="{urn:kdpw:xsd:trar.ins.001.03}PartyIdentification_EMIR_D" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DcsnMakr" type="{urn:kdpw:xsd:trar.ins.001.03}PersonOrOrganisation2Choice_TR" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyIdentification_EMIR", propOrder = {
    "acctOwnr",
    "dcsnMakr"
})
public class PartyIdentificationEMIR {

    @XmlElement(name = "AcctOwnr")
    protected List<PartyIdentificationEMIRD> acctOwnr;
    @XmlElement(name = "DcsnMakr")
    protected List<PersonOrOrganisation2ChoiceTR> dcsnMakr;

    /**
     * Gets the value of the acctOwnr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acctOwnr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcctOwnr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyIdentificationEMIRD }
     * 
     * 
     */
    public List<PartyIdentificationEMIRD> getAcctOwnr() {
        if (acctOwnr == null) {
            acctOwnr = new ArrayList<PartyIdentificationEMIRD>();
        }
        return this.acctOwnr;
    }

    /**
     * Gets the value of the dcsnMakr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcsnMakr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcsnMakr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonOrOrganisation2ChoiceTR }
     * 
     * 
     */
    public List<PersonOrOrganisation2ChoiceTR> getDcsnMakr() {
        if (dcsnMakr == null) {
            dcsnMakr = new ArrayList<PersonOrOrganisation2ChoiceTR>();
        }
        return this.dcsnMakr;
    }

}
