//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.19 at 03:49:39 PM CET 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of the legs of swap transaction.
 * 
 * <p>Java class for SwapLegIdentification2__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SwapLegIdentification2__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SwpIn" type="{urn:kdpw:xsd:trar.ins.001.03}FinancialInstrumentIdentification7Choice__1" minOccurs="0"/&gt;
 *         &lt;element name="SwpOut" type="{urn:kdpw:xsd:trar.ins.001.03}FinancialInstrumentIdentification7Choice__1" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwapLegIdentification2__1", propOrder = {
    "swpIn",
    "swpOut"
})
public class SwapLegIdentification21 {

    @XmlElement(name = "SwpIn")
    protected FinancialInstrumentIdentification7Choice1 swpIn;
    @XmlElement(name = "SwpOut")
    protected FinancialInstrumentIdentification7Choice1 swpOut;

    /**
     * Gets the value of the swpIn property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialInstrumentIdentification7Choice1 }
     *     
     */
    public FinancialInstrumentIdentification7Choice1 getSwpIn() {
        return swpIn;
    }

    /**
     * Sets the value of the swpIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialInstrumentIdentification7Choice1 }
     *     
     */
    public void setSwpIn(FinancialInstrumentIdentification7Choice1 value) {
        this.swpIn = value;
    }

    /**
     * Gets the value of the swpOut property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialInstrumentIdentification7Choice1 }
     *     
     */
    public FinancialInstrumentIdentification7Choice1 getSwpOut() {
        return swpOut;
    }

    /**
     * Sets the value of the swpOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialInstrumentIdentification7Choice1 }
     *     
     */
    public void setSwpOut(FinancialInstrumentIdentification7Choice1 value) {
        this.swpOut = value;
    }

}
