//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.14 at 01:33:12 PM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides details on the relevant action types for trade positions.
 * 
 * <p>Java class for TradePositionReportChoice_TR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradePositionReportChoice_TR"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="New" type="{urn:kdpw:xsd:trar.ins.001.03}TradeNewPosition_TR"/&gt;
 *           &lt;element name="Mod" type="{urn:kdpw:xsd:trar.ins.001.03}TradePositionModification_TR"/&gt;
 *           &lt;element name="Crrctn" type="{urn:kdpw:xsd:trar.ins.001.03}TradePositionCorrection_TR"/&gt;
 *           &lt;element name="EarlyTermntn" type="{urn:kdpw:xsd:trar.ins.001.03}TradePositionEarlyTermination_TR"/&gt;
 *           &lt;element name="ValtnUpd" type="{urn:kdpw:xsd:trar.ins.001.03}TradePositionValuationUpdate_TR"/&gt;
 *           &lt;element name="Err" type="{urn:kdpw:xsd:trar.ins.001.03}TradePositionError_TR"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradePositionReportChoice_TR", propOrder = {
    "_new",
    "mod",
    "crrctn",
    "earlyTermntn",
    "valtnUpd",
    "err"
})
public class TradePositionReportChoiceTR {

    @XmlElement(name = "New")
    protected TradeNewPositionTR _new;
    @XmlElement(name = "Mod")
    protected TradePositionModificationTR mod;
    @XmlElement(name = "Crrctn")
    protected TradePositionCorrectionTR crrctn;
    @XmlElement(name = "EarlyTermntn")
    protected TradePositionEarlyTerminationTR earlyTermntn;
    @XmlElement(name = "ValtnUpd")
    protected TradePositionValuationUpdateTR valtnUpd;
    @XmlElement(name = "Err")
    protected TradePositionErrorTR err;

    /**
     * Gets the value of the new property.
     * 
     * @return
     *     possible object is
     *     {@link TradeNewPositionTR }
     *     
     */
    public TradeNewPositionTR getNew() {
        return _new;
    }

    /**
     * Sets the value of the new property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeNewPositionTR }
     *     
     */
    public void setNew(TradeNewPositionTR value) {
        this._new = value;
    }

    /**
     * Gets the value of the mod property.
     * 
     * @return
     *     possible object is
     *     {@link TradePositionModificationTR }
     *     
     */
    public TradePositionModificationTR getMod() {
        return mod;
    }

    /**
     * Sets the value of the mod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePositionModificationTR }
     *     
     */
    public void setMod(TradePositionModificationTR value) {
        this.mod = value;
    }

    /**
     * Gets the value of the crrctn property.
     * 
     * @return
     *     possible object is
     *     {@link TradePositionCorrectionTR }
     *     
     */
    public TradePositionCorrectionTR getCrrctn() {
        return crrctn;
    }

    /**
     * Sets the value of the crrctn property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePositionCorrectionTR }
     *     
     */
    public void setCrrctn(TradePositionCorrectionTR value) {
        this.crrctn = value;
    }

    /**
     * Gets the value of the earlyTermntn property.
     * 
     * @return
     *     possible object is
     *     {@link TradePositionEarlyTerminationTR }
     *     
     */
    public TradePositionEarlyTerminationTR getEarlyTermntn() {
        return earlyTermntn;
    }

    /**
     * Sets the value of the earlyTermntn property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePositionEarlyTerminationTR }
     *     
     */
    public void setEarlyTermntn(TradePositionEarlyTerminationTR value) {
        this.earlyTermntn = value;
    }

    /**
     * Gets the value of the valtnUpd property.
     * 
     * @return
     *     possible object is
     *     {@link TradePositionValuationUpdateTR }
     *     
     */
    public TradePositionValuationUpdateTR getValtnUpd() {
        return valtnUpd;
    }

    /**
     * Sets the value of the valtnUpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePositionValuationUpdateTR }
     *     
     */
    public void setValtnUpd(TradePositionValuationUpdateTR value) {
        this.valtnUpd = value;
    }

    /**
     * Gets the value of the err property.
     * 
     * @return
     *     possible object is
     *     {@link TradePositionErrorTR }
     *     
     */
    public TradePositionErrorTR getErr() {
        return err;
    }

    /**
     * Sets the value of the err property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePositionErrorTR }
     *     
     */
    public void setErr(TradePositionErrorTR value) {
        this.err = value;
    }

}
