//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 01:49:47 PM CET 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Numer referencyjny transakcji
 * 
 * <p>Java class for TradeReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeReference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TradId" type="{urn:kdpw:xsd:trar.ins.001.02}Max52Text"/&gt;
 *         &lt;element name="CtrPtyTRId" type="{urn:kdpw:xsd:trar.ins.001.02}Max20Text"/&gt;
 *         &lt;element name="OthrCtrPtyTRId" type="{urn:kdpw:xsd:trar.ins.001.02}Max50Text"/&gt;
 *         &lt;element name="CtrPtySd" type="{urn:kdpw:xsd:trar.ins.001.02}Max1Text"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeReference", propOrder = {
    "tradId",
    "ctrPtyTRId",
    "othrCtrPtyTRId",
    "ctrPtySd"
})
public class TradeReference {

    @XmlElement(name = "TradId", required = true)
    protected String tradId;
    @XmlElement(name = "CtrPtyTRId", required = true)
    protected String ctrPtyTRId;
    @XmlElement(name = "OthrCtrPtyTRId", required = true)
    protected String othrCtrPtyTRId;
    @XmlElement(name = "CtrPtySd", required = true)
    protected String ctrPtySd;

    /**
     * Gets the value of the tradId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradId() {
        return tradId;
    }

    /**
     * Sets the value of the tradId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradId(String value) {
        this.tradId = value;
    }

    /**
     * Gets the value of the ctrPtyTRId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtrPtyTRId() {
        return ctrPtyTRId;
    }

    /**
     * Sets the value of the ctrPtyTRId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtrPtyTRId(String value) {
        this.ctrPtyTRId = value;
    }

    /**
     * Gets the value of the othrCtrPtyTRId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOthrCtrPtyTRId() {
        return othrCtrPtyTRId;
    }

    /**
     * Sets the value of the othrCtrPtyTRId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOthrCtrPtyTRId(String value) {
        this.othrCtrPtyTRId = value;
    }

    /**
     * Gets the value of the ctrPtySd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtrPtySd() {
        return ctrPtySd;
    }

    /**
     * Sets the value of the ctrPtySd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtrPtySd(String value) {
        this.ctrPtySd = value;
    }

}
