//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.29 at 02:25:35 PM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of collateral agreement between counterparties.
 * 
 * <p>Java class for TradeCollateralReport_TR_PC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeCollateralReport_TR_PC"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Collstn" type="{urn:kdpw:xsd:trar.ins.001.04}CollateralisationType1Code"/&gt;
 *         &lt;element name="PrtflColl" type="{urn:kdpw:xsd:trar.ins.001.04}YesNoIndicator" minOccurs="0"/&gt;
 *         &lt;element name="Prtfl" type="{urn:kdpw:xsd:trar.ins.001.04}KDPWMax52AlphaNumericAdditionalCharacters" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeCollateralReport_TR_PC", propOrder = {
    "collstn",
    "prtflColl",
    "prtfl"
})
public class TradeCollateralReportTRPC {

    @XmlElement(name = "Collstn", required = true)
    @XmlSchemaType(name = "string")
    protected CollateralisationType1Code collstn;
    @XmlElement(name = "PrtflColl")
    protected Boolean prtflColl;
    @XmlElement(name = "Prtfl")
    protected String prtfl;

    /**
     * Gets the value of the collstn property.
     * 
     * @return
     *     possible object is
     *     {@link CollateralisationType1Code }
     *     
     */
    public CollateralisationType1Code getCollstn() {
        return collstn;
    }

    /**
     * Sets the value of the collstn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollateralisationType1Code }
     *     
     */
    public void setCollstn(CollateralisationType1Code value) {
        this.collstn = value;
    }

    /**
     * Gets the value of the prtflColl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrtflColl() {
        return prtflColl;
    }

    /**
     * Sets the value of the prtflColl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrtflColl(Boolean value) {
        this.prtflColl = value;
    }

    /**
     * Gets the value of the prtfl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtfl() {
        return prtfl;
    }

    /**
     * Sets the value of the prtfl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtfl(String value) {
        this.prtfl = value;
    }

}
