//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.10 at 07:51:49 PM CEST 
//


package kdpw.xsd.trar_ins_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Position/transaction reporting under EMIR regulation.
 * 
 * <p>Java class for TradeReportChoice_TR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeReportChoice_TR"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Tx" type="{urn:kdpw:xsd:trar.ins.001.03}TradeTransactionReportChoice_TR"/&gt;
 *           &lt;element name="Pos" type="{urn:kdpw:xsd:trar.ins.001.03}TradePositionReportChoice_TR"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeReportChoice_TR", propOrder = {
    "tx",
    "pos"
})
public class TradeReportChoiceTR {

    @XmlElement(name = "Tx")
    protected TradeTransactionReportChoiceTR tx;
    @XmlElement(name = "Pos")
    protected TradePositionReportChoiceTR pos;

    /**
     * Gets the value of the tx property.
     * 
     * @return
     *     possible object is
     *     {@link TradeTransactionReportChoiceTR }
     *     
     */
    public TradeTransactionReportChoiceTR getTx() {
        return tx;
    }

    /**
     * Sets the value of the tx property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeTransactionReportChoiceTR }
     *     
     */
    public void setTx(TradeTransactionReportChoiceTR value) {
        this.tx = value;
    }

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link TradePositionReportChoiceTR }
     *     
     */
    public TradePositionReportChoiceTR getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePositionReportChoiceTR }
     *     
     */
    public void setPos(TradePositionReportChoiceTR value) {
        this.pos = value;
    }

}
