//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:33:46 AM CEST 
//


package kdpw.xsd.trar_rqs_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Informacje do filtra transakcji
 * 
 * <p>Java class for FilterInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="TradLstId" type="{urn:kdpw:xsd:trar.rqs.001.02}TradeListIdentification"/&gt;
 *           &lt;element name="TradId" type="{urn:kdpw:xsd:trar.rqs.001.02}TradeIdentification"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterInformation", propOrder = {
    "tradLstId",
    "tradId"
})
public class FilterInformation {

    @XmlElement(name = "TradLstId")
    protected TradeListIdentification tradLstId;
    @XmlElement(name = "TradId")
    protected TradeIdentification tradId;

    /**
     * Gets the value of the tradLstId property.
     * 
     * @return
     *     possible object is
     *     {@link TradeListIdentification }
     *     
     */
    public TradeListIdentification getTradLstId() {
        return tradLstId;
    }

    /**
     * Sets the value of the tradLstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeListIdentification }
     *     
     */
    public void setTradLstId(TradeListIdentification value) {
        this.tradLstId = value;
    }

    /**
     * Gets the value of the tradId property.
     * 
     * @return
     *     possible object is
     *     {@link TradeIdentification }
     *     
     */
    public TradeIdentification getTradId() {
        return tradId;
    }

    /**
     * Sets the value of the tradId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeIdentification }
     *     
     */
    public void setTradId(TradeIdentification value) {
        this.tradId = value;
    }

}
