//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:33:46 AM CEST 
//


package kdpw.xsd.trar_rqs_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Identyfikacja transakcji
 * 
 * <p>Java class for TradeIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeIdentification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{urn:kdpw:xsd:trar.rqs.001.02}Max52Text"/&gt;
 *         &lt;element name="PrvsId" type="{urn:kdpw:xsd:trar.rqs.001.02}Max52Text" minOccurs="0"/&gt;
 *         &lt;element name="TradRefNb" type="{urn:kdpw:xsd:trar.rqs.001.02}Max40Text"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="EligDt" type="{urn:kdpw:xsd:trar.rqs.001.02}ISODate"/&gt;
 *           &lt;element name="Prd" type="{urn:kdpw:xsd:trar.rqs.001.02}Period"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeIdentification", propOrder = {
    "id",
    "prvsId",
    "tradRefNb",
    "eligDt",
    "prd"
})
public class TradeIdentification {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "PrvsId")
    protected String prvsId;
    @XmlElement(name = "TradRefNb", required = true)
    protected String tradRefNb;
    @XmlElement(name = "EligDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar eligDt;
    @XmlElement(name = "Prd")
    protected Period prd;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the prvsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrvsId() {
        return prvsId;
    }

    /**
     * Sets the value of the prvsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrvsId(String value) {
        this.prvsId = value;
    }

    /**
     * Gets the value of the tradRefNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradRefNb() {
        return tradRefNb;
    }

    /**
     * Sets the value of the tradRefNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradRefNb(String value) {
        this.tradRefNb = value;
    }

    /**
     * Gets the value of the eligDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEligDt() {
        return eligDt;
    }

    /**
     * Sets the value of the eligDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEligDt(XMLGregorianCalendar value) {
        this.eligDt = value;
    }

    /**
     * Gets the value of the prd property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPrd() {
        return prd;
    }

    /**
     * Sets the value of the prd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPrd(Period value) {
        this.prd = value;
    }

}
